### ISSUE TITLE
Fix Homebrew release

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/cardinal-rs#20]
Add to the bottom of `release.yml` (after addressing TODO)

```yml
  bottle:
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is not available. https://github.com/actions/runner-images/issues/6426
        include:
          - name: arm64_monterey
            os: macos-12
            target: aarch64-apple-darwin
          - name: arm64_big_sur
            os: macos-11
            target: aarch64-apple-darwin
          - name: monterey
            os: macos-12
            target: x86_64-apple-darwin
          - name: big_sur
            os: macos-11
            target: x86_64-apple-darwin
          - name: catalina
            os: macos-10.15
            target: x86_64-apple-darwin
          - name: x86_64_linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    steps:
      - id: setup-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      # TODO need to update the url and sha256, otherwise brew install complains
      # try with checkout and git commands
      # https://lannonbr.com/blog/2019-12-09-git-commit-in-actions/
      - run: brew tap open-contracting/tap
      - env:
          CARGO_TARGET: ${{ matrix.target }}
        run: brew install --build-bottle --verbose ocdscardinal
      - run: brew bottle --no-rebuild --verbose ocdscardinal
      - env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.ref_name }} ocdscardinal--${{ github.ref_name }}.${{ matrix.name }}.bottle.tar.gz
```
